CFLAGS += $(ARCH_CFLAGS)
CFLAGS += -I"$(call local_dir,.)"

ifeq ($(REMOTEPROC_MASTER),y)
C_COMMON_SRCS :=  $(call local_dir,platform_info_remoteproc_master.c)
else
C_COMMON_SRCS := $(call local_dir,platform_info.c)
C_COMMON_SRCS += $(call local_dir,rsc_table.c)
endif

