/********************************************************************
 * Copyright (C) 2017 Texas Instruments Incorporated.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *  Name        : cslr_mailbox.h
*/
#ifndef CSLR_MAILBOX_H_
#define CSLR_MAILBOX_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdint.h>

#include "cslr.h"

/**************************************************************************
* Hardware Region  :
**************************************************************************/


/**************************************************************************
* Register Overlay Structure
**************************************************************************/

typedef struct {
    volatile uint32_t IRQ_STATUS_RAW;            /* Raw status for each event for user [a] */
    volatile uint32_t IRQ_STATUS_CLR;            /* Masked status for each event for user [a] */
    volatile uint32_t IRQ_ENABLE_SET;            /* Set interrupt enables. */
    volatile uint32_t IRQ_ENABLE_CLR;            /* Clear interrupt enables. */
} CSL_mailboxRegs_user;


typedef struct {
    volatile uint32_t REVISION;                  /* Peripheral ID register */
    volatile uint8_t  Resv_16[12];
    volatile uint32_t SYSCONFIG;                 /* Mailbox control register */
    volatile uint8_t  Resv_64[44];
    volatile uint32_t MESSAGE[16];               /* Message Mailbox */
    volatile uint32_t FIFO_STATUS[16];           /* FIFO status for Mailbox[a] */
    volatile uint32_t MSG_STATUS[16];            /* Number of messages in Mailbox[a] */
    CSL_mailboxRegs_user USER[4];
    volatile uint32_t IRQ_EOI;                   /* EOI register */
} CSL_mailboxRegs;


/**************************************************************************
* Register Macros
**************************************************************************/

#define CSL_MAILBOX_REVISION                                                   (0x00000000U)
#define CSL_MAILBOX_SYSCONFIG                                                  (0x00000010U)
#define CSL_MAILBOX_MESSAGE(MESSAGE)                                           (0x00000040U+((uintptr_t)(MESSAGE)*0x4U))
#define CSL_MAILBOX_FIFO_STATUS(FIFO_STATUS)                                   (0x00000080U+((uintptr_t)(FIFO_STATUS)*0x4U))
#define CSL_MAILBOX_MSG_STATUS(MSG_STATUS)                                     (0x000000C0U+((uintptr_t)(MSG_STATUS)*0x4U))
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW(USER)                                  (0x00000100U+((uintptr_t)(USER)*0x10U))
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR(USER)                                  (0x00000104U+((uintptr_t)(USER)*0x10U))
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET(USER)                                  (0x00000108U+((uintptr_t)(USER)*0x10U))
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR(USER)                                  (0x0000010CU+((uintptr_t)(USER)*0x10U))
#define CSL_MAILBOX_IRQ_EOI                                                    (0x00000140U)

/**************************************************************************
* Field Definition Macros
**************************************************************************/


/* IRQ_STATUS_RAW */

#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB0_MASK                   (0x00000001U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB0_SHIFT                  (0x00000000U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB0_MAX                    (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB0_MASK                  (0x00000002U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB0_SHIFT                 (0x00000001U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB0_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB1_MASK                   (0x00000004U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB1_SHIFT                  (0x00000002U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB1_MAX                    (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB1_MASK                  (0x00000008U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB1_SHIFT                 (0x00000003U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB1_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB2_MASK                   (0x00000010U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB2_SHIFT                  (0x00000004U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB2_MAX                    (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB2_MASK                  (0x00000020U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB2_SHIFT                 (0x00000005U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB2_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB3_MASK                   (0x00000040U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB3_SHIFT                  (0x00000006U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB3_MAX                    (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB3_MASK                  (0x00000080U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB3_SHIFT                 (0x00000007U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB3_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB4_MASK                   (0x00000100U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB4_SHIFT                  (0x00000008U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB4_MAX                    (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB4_MASK                  (0x00000200U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB4_SHIFT                 (0x00000009U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB4_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB5_MASK                   (0x00000400U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB5_SHIFT                  (0x0000000AU)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB5_MAX                    (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB5_MASK                  (0x00000800U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB5_SHIFT                 (0x0000000BU)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB5_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB6_MASK                   (0x00001000U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB6_SHIFT                  (0x0000000CU)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB6_MAX                    (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB6_MASK                  (0x00002000U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB6_SHIFT                 (0x0000000DU)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB6_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB7_MASK                   (0x00004000U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB7_SHIFT                  (0x0000000EU)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB7_MAX                    (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB7_MASK                  (0x00008000U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB7_SHIFT                 (0x0000000FU)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB7_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB8_MASK                   (0x00010000U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB8_SHIFT                  (0x00000010U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB8_MAX                    (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB8_MASK                  (0x00020000U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB8_SHIFT                 (0x00000011U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB8_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB9_MASK                   (0x00040000U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB9_SHIFT                  (0x00000012U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB9_MAX                    (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB9_MASK                  (0x00080000U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB9_SHIFT                 (0x00000013U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB9_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB10_MASK                  (0x00100000U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB10_SHIFT                 (0x00000014U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB10_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB10_MASK                 (0x00200000U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB10_SHIFT                (0x00000015U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB10_MAX                  (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB11_MASK                  (0x00400000U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB11_SHIFT                 (0x00000016U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB11_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB11_MASK                 (0x00800000U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB11_SHIFT                (0x00000017U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB11_MAX                  (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB12_MASK                  (0x01000000U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB12_SHIFT                 (0x00000018U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB12_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB12_MASK                 (0x02000000U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB12_SHIFT                (0x00000019U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB12_MAX                  (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB13_MASK                  (0x04000000U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB13_SHIFT                 (0x0000001AU)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB13_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB13_MASK                 (0x08000000U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB13_SHIFT                (0x0000001BU)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB13_MAX                  (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB14_MASK                  (0x10000000U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB14_SHIFT                 (0x0000001CU)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB14_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB14_MASK                 (0x20000000U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB14_SHIFT                (0x0000001DU)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB14_MAX                  (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB15_MASK                  (0x40000000U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB15_SHIFT                 (0x0000001EU)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NEWMSGSTATUSMB15_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB15_MASK                 (0x80000000U)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB15_SHIFT                (0x0000001FU)
#define CSL_MAILBOX_USER_IRQ_STATUS_RAW_NOTFULLSTATUSMB15_MAX                  (0x00000001U)

/* IRQ_STATUS_CLR */

#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB0_MASK                   (0x00000001U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB0_SHIFT                  (0x00000000U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB0_MAX                    (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB0_MASK                  (0x00000002U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB0_SHIFT                 (0x00000001U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB0_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB1_MASK                   (0x00000004U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB1_SHIFT                  (0x00000002U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB1_MAX                    (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB1_MASK                  (0x00000008U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB1_SHIFT                 (0x00000003U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB1_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB2_MASK                   (0x00000010U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB2_SHIFT                  (0x00000004U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB2_MAX                    (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB2_MASK                  (0x00000020U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB2_SHIFT                 (0x00000005U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB2_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB3_MASK                   (0x00000040U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB3_SHIFT                  (0x00000006U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB3_MAX                    (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB3_MASK                  (0x00000080U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB3_SHIFT                 (0x00000007U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB3_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB4_MASK                   (0x00000100U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB4_SHIFT                  (0x00000008U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB4_MAX                    (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB4_MASK                  (0x00000200U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB4_SHIFT                 (0x00000009U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB4_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB5_MASK                   (0x00000400U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB5_SHIFT                  (0x0000000AU)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB5_MAX                    (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB5_MASK                  (0x00000800U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB5_SHIFT                 (0x0000000BU)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB5_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB6_MASK                   (0x00001000U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB6_SHIFT                  (0x0000000CU)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB6_MAX                    (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB6_MASK                  (0x00002000U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB6_SHIFT                 (0x0000000DU)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB6_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB7_MASK                   (0x00004000U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB7_SHIFT                  (0x0000000EU)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB7_MAX                    (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB7_MASK                  (0x00008000U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB7_SHIFT                 (0x0000000FU)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB7_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB8_MASK                   (0x00010000U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB8_SHIFT                  (0x00000010U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB8_MAX                    (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB8_MASK                  (0x00020000U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB8_SHIFT                 (0x00000011U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB8_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB9_MASK                   (0x00040000U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB9_SHIFT                  (0x00000012U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB9_MAX                    (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB9_MASK                  (0x00080000U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB9_SHIFT                 (0x00000013U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB9_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB10_MASK                  (0x00100000U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB10_SHIFT                 (0x00000014U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB10_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB10_MASK                 (0x00200000U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB10_SHIFT                (0x00000015U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB10_MAX                  (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB11_MASK                  (0x00400000U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB11_SHIFT                 (0x00000016U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB11_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB11_MASK                 (0x00800000U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB11_SHIFT                (0x00000017U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB11_MAX                  (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB12_MASK                  (0x01000000U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB12_SHIFT                 (0x00000018U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB12_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB12_MASK                 (0x02000000U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB12_SHIFT                (0x00000019U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB12_MAX                  (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB13_MASK                  (0x04000000U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB13_SHIFT                 (0x0000001AU)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB13_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB13_MASK                 (0x08000000U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB13_SHIFT                (0x0000001BU)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB13_MAX                  (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB14_MASK                  (0x10000000U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB14_SHIFT                 (0x0000001CU)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB14_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB14_MASK                 (0x20000000U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB14_SHIFT                (0x0000001DU)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB14_MAX                  (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB15_MASK                  (0x40000000U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB15_SHIFT                 (0x0000001EU)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NEWMSGSTATUSMB15_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB15_MASK                 (0x80000000U)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB15_SHIFT                (0x0000001FU)
#define CSL_MAILBOX_USER_IRQ_STATUS_CLR_NOTFULLSTATUSMB15_MAX                  (0x00000001U)

/* IRQ_ENABLE_SET */

#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB0_MASK                   (0x00000001U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB0_SHIFT                  (0x00000000U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB0_MAX                    (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB0_MASK                  (0x00000002U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB0_SHIFT                 (0x00000001U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB0_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB1_MASK                   (0x00000004U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB1_SHIFT                  (0x00000002U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB1_MAX                    (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB1_MASK                  (0x00000008U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB1_SHIFT                 (0x00000003U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB1_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB2_MASK                   (0x00000010U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB2_SHIFT                  (0x00000004U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB2_MAX                    (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB2_MASK                  (0x00000020U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB2_SHIFT                 (0x00000005U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB2_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB3_MASK                   (0x00000040U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB3_SHIFT                  (0x00000006U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB3_MAX                    (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB3_MASK                  (0x00000080U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB3_SHIFT                 (0x00000007U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB3_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB4_MASK                   (0x00000100U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB4_SHIFT                  (0x00000008U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB4_MAX                    (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB4_MASK                  (0x00000200U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB4_SHIFT                 (0x00000009U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB4_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB5_MASK                   (0x00000400U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB5_SHIFT                  (0x0000000AU)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB5_MAX                    (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB5_MASK                  (0x00000800U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB5_SHIFT                 (0x0000000BU)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB5_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB6_MASK                   (0x00001000U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB6_SHIFT                  (0x0000000CU)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB6_MAX                    (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB6_MASK                  (0x00002000U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB6_SHIFT                 (0x0000000DU)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB6_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB7_MASK                   (0x00004000U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB7_SHIFT                  (0x0000000EU)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB7_MAX                    (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB7_MASK                  (0x00008000U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB7_SHIFT                 (0x0000000FU)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB7_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB8_MASK                   (0x00010000U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB8_SHIFT                  (0x00000010U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB8_MAX                    (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB8_MASK                  (0x00020000U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB8_SHIFT                 (0x00000011U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB8_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB9_MASK                   (0x00040000U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB9_SHIFT                  (0x00000012U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB9_MAX                    (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB9_MASK                  (0x00080000U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB9_SHIFT                 (0x00000013U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB9_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB10_MASK                  (0x00100000U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB10_SHIFT                 (0x00000014U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB10_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB10_MASK                 (0x00200000U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB10_SHIFT                (0x00000015U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB10_MAX                  (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB11_MASK                  (0x00400000U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB11_SHIFT                 (0x00000016U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB11_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB11_MASK                 (0x00800000U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB11_SHIFT                (0x00000017U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB11_MAX                  (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB12_MASK                  (0x01000000U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB12_SHIFT                 (0x00000018U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB12_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB12_MASK                 (0x02000000U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB12_SHIFT                (0x00000019U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB12_MAX                  (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB13_MASK                  (0x04000000U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB13_SHIFT                 (0x0000001AU)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB13_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB13_MASK                 (0x08000000U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB13_SHIFT                (0x0000001BU)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB13_MAX                  (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB14_MASK                  (0x10000000U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB14_SHIFT                 (0x0000001CU)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB14_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB14_MASK                 (0x20000000U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB14_SHIFT                (0x0000001DU)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB14_MAX                  (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB15_MASK                  (0x40000000U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB15_SHIFT                 (0x0000001EU)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NEWMSGENABLEMB15_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB15_MASK                 (0x80000000U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB15_SHIFT                (0x0000001FU)
#define CSL_MAILBOX_USER_IRQ_ENABLE_SET_NOTFULLENABLEMB15_MAX                  (0x00000001U)

/* IRQ_ENABLE_CLR */

#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB0_MASK                   (0x00000001U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB0_SHIFT                  (0x00000000U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB0_MAX                    (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB0_MASK                  (0x00000002U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB0_SHIFT                 (0x00000001U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB0_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB1_MASK                   (0x00000004U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB1_SHIFT                  (0x00000002U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB1_MAX                    (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB1_MASK                  (0x00000008U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB1_SHIFT                 (0x00000003U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB1_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB2_MASK                   (0x00000010U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB2_SHIFT                  (0x00000004U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB2_MAX                    (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB2_MASK                  (0x00000020U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB2_SHIFT                 (0x00000005U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB2_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB3_MASK                   (0x00000040U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB3_SHIFT                  (0x00000006U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB3_MAX                    (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB3_MASK                  (0x00000080U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB3_SHIFT                 (0x00000007U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB3_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB4_MASK                   (0x00000100U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB4_SHIFT                  (0x00000008U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB4_MAX                    (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB4_MASK                  (0x00000200U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB4_SHIFT                 (0x00000009U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB4_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB5_MASK                   (0x00000400U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB5_SHIFT                  (0x0000000AU)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB5_MAX                    (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB5_MASK                  (0x00000800U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB5_SHIFT                 (0x0000000BU)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB5_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB6_MASK                   (0x00001000U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB6_SHIFT                  (0x0000000CU)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB6_MAX                    (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB6_MASK                  (0x00002000U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB6_SHIFT                 (0x0000000DU)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB6_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB7_MASK                   (0x00004000U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB7_SHIFT                  (0x0000000EU)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB7_MAX                    (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB7_MASK                  (0x00008000U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB7_SHIFT                 (0x0000000FU)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB7_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB8_MASK                   (0x00010000U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB8_SHIFT                  (0x00000010U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB8_MAX                    (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB8_MASK                  (0x00020000U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB8_SHIFT                 (0x00000011U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB8_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB9_MASK                   (0x00040000U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB9_SHIFT                  (0x00000012U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB9_MAX                    (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB9_MASK                  (0x00080000U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB9_SHIFT                 (0x00000013U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB9_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB10_MASK                  (0x00100000U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB10_SHIFT                 (0x00000014U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB10_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB10_MASK                 (0x00200000U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB10_SHIFT                (0x00000015U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB10_MAX                  (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB11_MASK                  (0x00400000U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB11_SHIFT                 (0x00000016U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB11_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB11_MASK                 (0x00800000U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB11_SHIFT                (0x00000017U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB11_MAX                  (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB12_MASK                  (0x01000000U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB12_SHIFT                 (0x00000018U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB12_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB12_MASK                 (0x02000000U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB12_SHIFT                (0x00000019U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB12_MAX                  (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB13_MASK                  (0x04000000U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB13_SHIFT                 (0x0000001AU)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB13_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB13_MASK                 (0x08000000U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB13_SHIFT                (0x0000001BU)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB13_MAX                  (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB14_MASK                  (0x10000000U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB14_SHIFT                 (0x0000001CU)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB14_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB14_MASK                 (0x20000000U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB14_SHIFT                (0x0000001DU)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB14_MAX                  (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB15_MASK                  (0x40000000U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB15_SHIFT                 (0x0000001EU)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NEWMSGENABLEMB15_MAX                   (0x00000001U)

#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB15_MASK                 (0x80000000U)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB15_SHIFT                (0x0000001FU)
#define CSL_MAILBOX_USER_IRQ_ENABLE_CLR_NOTFULLENABLEMB15_MAX                  (0x00000001U)

/* REVISION */

#define CSL_MAILBOX_REVISION_SCHEME_MASK                                       (0xC0000000U)
#define CSL_MAILBOX_REVISION_SCHEME_SHIFT                                      (0x0000001EU)
#define CSL_MAILBOX_REVISION_SCHEME_MAX                                        (0x00000003U)

#define CSL_MAILBOX_REVISION_BU_MASK                                           (0x30000000U)
#define CSL_MAILBOX_REVISION_BU_SHIFT                                          (0x0000001CU)
#define CSL_MAILBOX_REVISION_BU_MAX                                            (0x00000003U)

#define CSL_MAILBOX_REVISION_FUNCTION_MASK                                     (0x0FFF0000U)
#define CSL_MAILBOX_REVISION_FUNCTION_SHIFT                                    (0x00000010U)
#define CSL_MAILBOX_REVISION_FUNCTION_MAX                                      (0x00000FFFU)

#define CSL_MAILBOX_REVISION_RTL_VER_MASK                                      (0x0000F800U)
#define CSL_MAILBOX_REVISION_RTL_VER_SHIFT                                     (0x0000000BU)
#define CSL_MAILBOX_REVISION_RTL_VER_MAX                                       (0x0000001FU)

#define CSL_MAILBOX_REVISION_MAJOR_REV_MASK                                    (0x00000700U)
#define CSL_MAILBOX_REVISION_MAJOR_REV_SHIFT                                   (0x00000008U)
#define CSL_MAILBOX_REVISION_MAJOR_REV_MAX                                     (0x00000007U)

#define CSL_MAILBOX_REVISION_CUSTOM_MASK                                       (0x000000C0U)
#define CSL_MAILBOX_REVISION_CUSTOM_SHIFT                                      (0x00000006U)
#define CSL_MAILBOX_REVISION_CUSTOM_MAX                                        (0x00000003U)

#define CSL_MAILBOX_REVISION_MINOR_REV_MASK                                    (0x0000003FU)
#define CSL_MAILBOX_REVISION_MINOR_REV_SHIFT                                   (0x00000000U)
#define CSL_MAILBOX_REVISION_MINOR_REV_MAX                                     (0x0000003FU)

/* SYSCONFIG */

#define CSL_MAILBOX_SYSCONFIG_SOFT_RESET_MASK                                  (0x00000001U)
#define CSL_MAILBOX_SYSCONFIG_SOFT_RESET_SHIFT                                 (0x00000000U)
#define CSL_MAILBOX_SYSCONFIG_SOFT_RESET_MAX                                   (0x00000001U)

/* MESSAGE */

#define CSL_MAILBOX_MESSAGE_VALUE_MASK                                         (0xFFFFFFFFU)
#define CSL_MAILBOX_MESSAGE_VALUE_SHIFT                                        (0x00000000U)
#define CSL_MAILBOX_MESSAGE_VALUE_MAX                                          (0xFFFFFFFFU)

/* FIFO_STATUS */

#define CSL_MAILBOX_FIFO_STATUS_FULL_MASK                                      (0x00000001U)
#define CSL_MAILBOX_FIFO_STATUS_FULL_SHIFT                                     (0x00000000U)
#define CSL_MAILBOX_FIFO_STATUS_FULL_MAX                                       (0x00000001U)

/* MSG_STATUS */

#define CSL_MAILBOX_MSG_STATUS_NUM_MESSAGES_MASK                               (0x0000003FU)
#define CSL_MAILBOX_MSG_STATUS_NUM_MESSAGES_SHIFT                              (0x00000000U)
#define CSL_MAILBOX_MSG_STATUS_NUM_MESSAGES_MAX                                (0x0000003FU)

/* IRQ_EOI */

#define CSL_MAILBOX_IRQ_EOI_EOI0_MASK                                          (0x00000001U)
#define CSL_MAILBOX_IRQ_EOI_EOI0_SHIFT                                         (0x00000000U)
#define CSL_MAILBOX_IRQ_EOI_EOI0_MAX                                           (0x00000001U)

#define CSL_MAILBOX_IRQ_EOI_EOI1_MASK                                          (0x00000002U)
#define CSL_MAILBOX_IRQ_EOI_EOI1_SHIFT                                         (0x00000001U)
#define CSL_MAILBOX_IRQ_EOI_EOI1_MAX                                           (0x00000001U)

#define CSL_MAILBOX_IRQ_EOI_EOI2_MASK                                          (0x00000004U)
#define CSL_MAILBOX_IRQ_EOI_EOI2_SHIFT                                         (0x00000002U)
#define CSL_MAILBOX_IRQ_EOI_EOI2_MAX                                           (0x00000001U)

#define CSL_MAILBOX_IRQ_EOI_EOI3_MASK                                          (0x00000008U)
#define CSL_MAILBOX_IRQ_EOI_EOI3_SHIFT                                         (0x00000003U)
#define CSL_MAILBOX_IRQ_EOI_EOI3_MAX                                           (0x00000001U)

#ifdef __cplusplus
}
#endif
#endif
